# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Wed Jan 14 00:31:07 2015
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 736)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.currentDisplay = QtWidgets.QLabel(self.centralwidget)
        self.currentDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.currentDisplay.setObjectName("currentDisplay")
        self.horizontalLayout.addWidget(self.currentDisplay)
        self.prevPageButton = QtWidgets.QPushButton(self.centralwidget)
        self.prevPageButton.setObjectName("prevPageButton")
        self.horizontalLayout.addWidget(self.prevPageButton)
        self.prevCardButton = QtWidgets.QPushButton(self.centralwidget)
        self.prevCardButton.setObjectName("prevCardButton")
        self.horizontalLayout.addWidget(self.prevCardButton)
        self.nextCardButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextCardButton.setObjectName("nextCardButton")
        self.horizontalLayout.addWidget(self.nextCardButton)
        self.nextPageButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextPageButton.setObjectName("nextPageButton")
        self.horizontalLayout.addWidget(self.nextPageButton)
        self.rotateButton = QtWidgets.QPushButton(self.centralwidget)
        self.rotateButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/rotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotateButton.setIcon(icon)
        self.rotateButton.setObjectName("rotateButton")
        self.horizontalLayout.addWidget(self.rotateButton)
        self.zoomOutButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoomOutButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/zoomout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomOutButton.setIcon(icon1)
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.horizontalLayout.addWidget(self.zoomOutButton)
        self.zoomInButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoomInButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/zoomin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomInButton.setIcon(icon2)
        self.zoomInButton.setObjectName("zoomInButton")
        self.horizontalLayout.addWidget(self.zoomInButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.c = QtWidgets.QTabWidget(self.centralwidget)
        self.c.setObjectName("c")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        self.inputGView = QtWidgets.QGraphicsView(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputGView.sizePolicy().hasHeightForWidth())
        self.inputGView.setSizePolicy(sizePolicy)
        self.inputGView.setObjectName("inputGView")
        self.verticalLayout_5.addWidget(self.inputGView)
        self.c.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.cardGView = QtWidgets.QGraphicsView(self.tab_2)
        self.cardGView.setObjectName("cardGView")
        self.verticalLayout_4.addWidget(self.cardGView)
        self.c.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.outputGView = QtWidgets.QGraphicsView(self.tab_3)
        self.outputGView.setObjectName("outputGView")
        self.verticalLayout_2.addWidget(self.outputGView)
        self.c.addTab(self.tab_3, "")
        self.verticalLayout_6.addWidget(self.c)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(296, 0))
        self.toolBox.setObjectName("toolBox")
        self.page1 = QtWidgets.QWidget()
        self.page1.setGeometry(QtCore.QRect(0, 0, 296, 609))
        self.page1.setObjectName("page1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.page1)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.inputCardWidth = QtWidgets.QSpinBox(self.groupBox)
        self.inputCardWidth.setMinimum(1)
        self.inputCardWidth.setMaximum(9999)
        self.inputCardWidth.setProperty("value", 750)
        self.inputCardWidth.setObjectName("inputCardWidth")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.inputCardWidth)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.inputCardHeight = QtWidgets.QSpinBox(self.groupBox)
        self.inputCardHeight.setMinimum(1)
        self.inputCardHeight.setMaximum(9999)
        self.inputCardHeight.setProperty("value", 1050)
        self.inputCardHeight.setObjectName("inputCardHeight")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.inputCardHeight)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.page1)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_4.setObjectName("formLayout_4")
        self.inputRows = QtWidgets.QSpinBox(self.groupBox_4)
        self.inputRows.setMinimum(1)
        self.inputRows.setMaximum(9999)
        self.inputRows.setProperty("value", 3)
        self.inputRows.setObjectName("inputRows")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.inputRows)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_7)
        self.inputColumns = QtWidgets.QSpinBox(self.groupBox_4)
        self.inputColumns.setMinimum(1)
        self.inputColumns.setMaximum(9999)
        self.inputColumns.setProperty("value", 3)
        self.inputColumns.setObjectName("inputColumns")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.inputColumns)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_8)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page1)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.inputShiftHor = QtWidgets.QSpinBox(self.groupBox_2)
        self.inputShiftHor.setMinimum(-9999)
        self.inputShiftHor.setMaximum(9999)
        self.inputShiftHor.setObjectName("inputShiftHor")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.inputShiftHor)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.inputShiftVert = QtWidgets.QSpinBox(self.groupBox_2)
        self.inputShiftVert.setMinimum(-9999)
        self.inputShiftVert.setMaximum(9999)
        self.inputShiftVert.setObjectName("inputShiftVert")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.inputShiftVert)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_5)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.page1)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.inputInnerWidth = QtWidgets.QSpinBox(self.groupBox_3)
        self.inputInnerWidth.setMaximum(9999)
        self.inputInnerWidth.setObjectName("inputInnerWidth")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.inputInnerWidth)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.inputInnerHeight = QtWidgets.QSpinBox(self.groupBox_3)
        self.inputInnerHeight.setMaximum(9999)
        self.inputInnerHeight.setObjectName("inputInnerHeight")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.inputInnerHeight)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_6)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.openInputLayoutButton = QtWidgets.QPushButton(self.page1)
        self.openInputLayoutButton.setObjectName("openInputLayoutButton")
        self.verticalLayout_7.addWidget(self.openInputLayoutButton)
        self.saveInputLayoutButton = QtWidgets.QPushButton(self.page1)
        self.saveInputLayoutButton.setObjectName("saveInputLayoutButton")
        self.verticalLayout_7.addWidget(self.saveInputLayoutButton)
        self.verticalLayout.addLayout(self.verticalLayout_7)
        self.toolBox.addItem(self.page1, "")
        self.page2 = QtWidgets.QWidget()
        self.page2.setGeometry(QtCore.QRect(0, 0, 296, 609))
        self.page2.setObjectName("page2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_5 = QtWidgets.QGroupBox(self.page2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.outputCardWidth = QtWidgets.QSpinBox(self.groupBox_5)
        self.outputCardWidth.setMinimum(1)
        self.outputCardWidth.setMaximum(9999)
        self.outputCardWidth.setProperty("value", 750)
        self.outputCardWidth.setObjectName("outputCardWidth")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.outputCardWidth)
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setObjectName("label_9")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_9)
        self.outputCardHeight = QtWidgets.QSpinBox(self.groupBox_5)
        self.outputCardHeight.setMinimum(1)
        self.outputCardHeight.setMaximum(9999)
        self.outputCardHeight.setProperty("value", 1050)
        self.outputCardHeight.setObjectName("outputCardHeight")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.outputCardHeight)
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setObjectName("label_10")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_10)
        self.verticalLayout_8.addWidget(self.groupBox_5)
        self.groupBox_8 = QtWidgets.QGroupBox(self.page2)
        self.groupBox_8.setObjectName("groupBox_8")
        self.formLayout_8 = QtWidgets.QFormLayout(self.groupBox_8)
        self.formLayout_8.setObjectName("formLayout_8")
        self.outputRows = QtWidgets.QSpinBox(self.groupBox_8)
        self.outputRows.setMinimum(1)
        self.outputRows.setMaximum(9999)
        self.outputRows.setProperty("value", 3)
        self.outputRows.setObjectName("outputRows")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.outputRows)
        self.label_15 = QtWidgets.QLabel(self.groupBox_8)
        self.label_15.setObjectName("label_15")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_15)
        self.outputColumns = QtWidgets.QSpinBox(self.groupBox_8)
        self.outputColumns.setMinimum(1)
        self.outputColumns.setMaximum(9999)
        self.outputColumns.setProperty("value", 3)
        self.outputColumns.setObjectName("outputColumns")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.outputColumns)
        self.label_16 = QtWidgets.QLabel(self.groupBox_8)
        self.label_16.setObjectName("label_16")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_16)
        self.verticalLayout_8.addWidget(self.groupBox_8)
        self.groupBox_7 = QtWidgets.QGroupBox(self.page2)
        self.groupBox_7.setObjectName("groupBox_7")
        self.formLayout_7 = QtWidgets.QFormLayout(self.groupBox_7)
        self.formLayout_7.setObjectName("formLayout_7")
        self.outputShiftHor = QtWidgets.QSpinBox(self.groupBox_7)
        self.outputShiftHor.setMinimum(-9999)
        self.outputShiftHor.setMaximum(9999)
        self.outputShiftHor.setObjectName("outputShiftHor")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.outputShiftHor)
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        self.label_13.setObjectName("label_13")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_13)
        self.outputShiftVert = QtWidgets.QSpinBox(self.groupBox_7)
        self.outputShiftVert.setMinimum(-9999)
        self.outputShiftVert.setMaximum(9999)
        self.outputShiftVert.setObjectName("outputShiftVert")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.outputShiftVert)
        self.label_14 = QtWidgets.QLabel(self.groupBox_7)
        self.label_14.setObjectName("label_14")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_14)
        self.verticalLayout_8.addWidget(self.groupBox_7)
        self.groupBox_6 = QtWidgets.QGroupBox(self.page2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.groupBox_6)
        self.formLayout_6.setObjectName("formLayout_6")
        self.outputInnerWidth = QtWidgets.QSpinBox(self.groupBox_6)
        self.outputInnerWidth.setMaximum(9999)
        self.outputInnerWidth.setObjectName("outputInnerWidth")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.outputInnerWidth)
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setObjectName("label_11")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_11)
        self.outputInnerHeight = QtWidgets.QSpinBox(self.groupBox_6)
        self.outputInnerHeight.setMaximum(9999)
        self.outputInnerHeight.setObjectName("outputInnerHeight")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.outputInnerHeight)
        self.label_12 = QtWidgets.QLabel(self.groupBox_6)
        self.label_12.setObjectName("label_12")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_12)
        self.outputInnerColor = QtWidgets.QLineEdit(self.groupBox_6)
        self.outputInnerColor.setObjectName("outputInnerColor")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.outputInnerColor)
        self.label_20 = QtWidgets.QLabel(self.groupBox_6)
        self.label_20.setObjectName("label_20")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_20)
        self.outputInnerCorners = QtWidgets.QSpinBox(self.groupBox_6)
        self.outputInnerCorners.setObjectName("outputInnerCorners")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.outputInnerCorners)
        self.label_22 = QtWidgets.QLabel(self.groupBox_6)
        self.label_22.setObjectName("label_22")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_22)
        self.verticalLayout_8.addWidget(self.groupBox_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.copyLayoutButton = QtWidgets.QPushButton(self.page2)
        self.copyLayoutButton.setObjectName("copyLayoutButton")
        self.verticalLayout_3.addWidget(self.copyLayoutButton)
        self.openOutputLayoutButton = QtWidgets.QPushButton(self.page2)
        self.openOutputLayoutButton.setObjectName("openOutputLayoutButton")
        self.verticalLayout_3.addWidget(self.openOutputLayoutButton)
        self.saveOutputLayoutButton = QtWidgets.QPushButton(self.page2)
        self.saveOutputLayoutButton.setObjectName("saveOutputLayoutButton")
        self.verticalLayout_3.addWidget(self.saveOutputLayoutButton)
        self.verticalLayout_8.addLayout(self.verticalLayout_3)
        self.toolBox.addItem(self.page2, "")
        self.horizontalLayout_2.addWidget(self.toolBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1059, 25))
        self.menubar.setObjectName("menubar")
        self.menuTest = QtWidgets.QMenu(self.menubar)
        self.menuTest.setObjectName("menuTest")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSaveCards = QtWidgets.QAction(MainWindow)
        self.actionSaveCards.setObjectName("actionSaveCards")
        self.actionSaveOutput = QtWidgets.QAction(MainWindow)
        self.actionSaveOutput.setObjectName("actionSaveOutput")
        self.menuTest.addAction(self.actionOpen)
        self.menuTest.addSeparator()
        self.menuTest.addAction(self.actionSaveOutput)
        self.menuTest.addAction(self.actionSaveCards)
        self.menuTest.addSeparator()
        self.menuTest.addAction(self.actionExit)
        self.menubar.addAction(self.menuTest.menuAction())

        self.retranslateUi(MainWindow)
        self.c.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YACK"))
        self.currentDisplay.setText(_translate("MainWindow", "0/1 - 0/9"))
        self.prevPageButton.setText(_translate("MainWindow", "<<"))
        self.prevCardButton.setText(_translate("MainWindow", "<"))
        self.nextCardButton.setText(_translate("MainWindow", ">"))
        self.nextPageButton.setText(_translate("MainWindow", ">>"))
        self.label_17.setText(_translate("MainWindow", "This displays the current page of the opened file"))
        self.c.setTabText(self.c.indexOf(self.tab), _translate("MainWindow", "Input"))
        self.label_18.setText(_translate("MainWindow", "This displays one card cropped using current input layout"))
        self.c.setTabText(self.c.indexOf(self.tab_2), _translate("MainWindow", "Card"))
        self.label_19.setText(_translate("MainWindow", "This displays how the output will look like"))
        self.c.setTabText(self.c.indexOf(self.tab_3), _translate("MainWindow", "Output"))
        self.groupBox.setTitle(_translate("MainWindow", "Cards"))
        self.label.setText(_translate("MainWindow", "Width"))
        self.label_2.setText(_translate("MainWindow", "Height"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Grid size"))
        self.label_7.setText(_translate("MainWindow", "Rows"))
        self.label_8.setText(_translate("MainWindow", "Columns"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Shift"))
        self.label_3.setText(_translate("MainWindow", "Horizontal"))
        self.label_5.setText(_translate("MainWindow", "Vertical"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Inner margin"))
        self.label_4.setText(_translate("MainWindow", "Width"))
        self.label_6.setText(_translate("MainWindow", "Height"))
        self.openInputLayoutButton.setText(_translate("MainWindow", "Open layout"))
        self.saveInputLayoutButton.setText(_translate("MainWindow", "Save layout"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page1), _translate("MainWindow", "Input layout"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Cards"))
        self.label_9.setText(_translate("MainWindow", "Width"))
        self.label_10.setText(_translate("MainWindow", "Height"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Grid size"))
        self.label_15.setText(_translate("MainWindow", "Rows"))
        self.label_16.setText(_translate("MainWindow", "Columns"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Shift"))
        self.label_13.setText(_translate("MainWindow", "Horizontal"))
        self.label_14.setText(_translate("MainWindow", "Vertical"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Inner margin"))
        self.label_11.setText(_translate("MainWindow", "Width"))
        self.label_12.setText(_translate("MainWindow", "Height"))
        self.outputInnerColor.setText(_translate("MainWindow", "#ffffff"))
        self.label_20.setText(_translate("MainWindow", "Color"))
        self.label_22.setText(_translate("MainWindow", "Round corners"))
        self.copyLayoutButton.setText(_translate("MainWindow", "Copy from input"))
        self.openOutputLayoutButton.setText(_translate("MainWindow", "Open layout"))
        self.saveOutputLayoutButton.setText(_translate("MainWindow", "Save layout"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page2), _translate("MainWindow", "Output layout"))
        self.menuTest.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionSaveCards.setText(_translate("MainWindow", "Save cards..."))
        self.actionSaveCards.setToolTip(_translate("MainWindow", "Save each card as a separate file (for POD services)"))
        self.actionSaveOutput.setText(_translate("MainWindow", "Save output"))

