# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Thu Jan  8 13:42:09 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 736)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.showFullPageCB = QtWidgets.QCheckBox(self.centralwidget)
        self.showFullPageCB.setObjectName("showFullPageCB")
        self.horizontalLayout.addWidget(self.showFullPageCB)
        self.rotateButton = QtWidgets.QPushButton(self.centralwidget)
        self.rotateButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/rotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotateButton.setIcon(icon)
        self.rotateButton.setObjectName("rotateButton")
        self.horizontalLayout.addWidget(self.rotateButton)
        self.zoomOutButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoomOutButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/zoomout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomOutButton.setIcon(icon1)
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.horizontalLayout.addWidget(self.zoomOutButton)
        self.zoomInButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoomInButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/zoomin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomInButton.setIcon(icon2)
        self.zoomInButton.setObjectName("zoomInButton")
        self.horizontalLayout.addWidget(self.zoomInButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setObjectName("toolBox")
        self.page1 = QtWidgets.QWidget()
        self.page1.setGeometry(QtCore.QRect(0, 0, 165, 621))
        self.page1.setObjectName("page1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.page1)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.inputCardWidth = QtWidgets.QSpinBox(self.groupBox)
        self.inputCardWidth.setMinimum(1)
        self.inputCardWidth.setMaximum(9999)
        self.inputCardWidth.setObjectName("inputCardWidth")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.inputCardWidth)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.inputCardHeight = QtWidgets.QSpinBox(self.groupBox)
        self.inputCardHeight.setMinimum(1)
        self.inputCardHeight.setMaximum(9999)
        self.inputCardHeight.setObjectName("inputCardHeight")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.inputCardHeight)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.page1)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_4.setObjectName("formLayout_4")
        self.inputRows = QtWidgets.QSpinBox(self.groupBox_4)
        self.inputRows.setMinimum(1)
        self.inputRows.setMaximum(9999)
        self.inputRows.setProperty("value", 3)
        self.inputRows.setObjectName("inputRows")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.inputRows)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_7)
        self.inputColumns = QtWidgets.QSpinBox(self.groupBox_4)
        self.inputColumns.setMinimum(1)
        self.inputColumns.setMaximum(9999)
        self.inputColumns.setProperty("value", 3)
        self.inputColumns.setObjectName("inputColumns")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.inputColumns)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_8)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page1)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.inputOuterLeft = QtWidgets.QSpinBox(self.groupBox_2)
        self.inputOuterLeft.setMaximum(9999)
        self.inputOuterLeft.setObjectName("inputOuterLeft")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.inputOuterLeft)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.inputOuterTop = QtWidgets.QSpinBox(self.groupBox_2)
        self.inputOuterTop.setMaximum(9999)
        self.inputOuterTop.setObjectName("inputOuterTop")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.inputOuterTop)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_5)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.page1)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.inputInnerWidth = QtWidgets.QSpinBox(self.groupBox_3)
        self.inputInnerWidth.setMaximum(9999)
        self.inputInnerWidth.setObjectName("inputInnerWidth")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.inputInnerWidth)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.inputInnerHeight = QtWidgets.QSpinBox(self.groupBox_3)
        self.inputInnerHeight.setMaximum(9999)
        self.inputInnerHeight.setObjectName("inputInnerHeight")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.inputInnerHeight)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_6)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.toolBox.addItem(self.page1, "")
        self.page2 = QtWidgets.QWidget()
        self.page2.setGeometry(QtCore.QRect(0, 0, 93, 621))
        self.page2.setObjectName("page2")
        self.toolBox.addItem(self.page2, "")
        self.horizontalLayout_2.addWidget(self.toolBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 19))
        self.menubar.setObjectName("menubar")
        self.menuTest = QtWidgets.QMenu(self.menubar)
        self.menuTest.setObjectName("menuTest")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuTest.addAction(self.actionOpen)
        self.menuTest.addSeparator()
        self.menuTest.addAction(self.actionExit)
        self.menubar.addAction(self.menuTest.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YACK"))
        self.showFullPageCB.setText(_translate("MainWindow", "Show full page"))
        self.groupBox.setTitle(_translate("MainWindow", "Cards"))
        self.label.setText(_translate("MainWindow", "Width"))
        self.label_2.setText(_translate("MainWindow", "Height"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Grid size"))
        self.label_7.setText(_translate("MainWindow", "Rows"))
        self.label_8.setText(_translate("MainWindow", "Columns"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Outer margin"))
        self.label_3.setText(_translate("MainWindow", "Left"))
        self.label_5.setText(_translate("MainWindow", "Top"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Inner margin"))
        self.label_4.setText(_translate("MainWindow", "Width"))
        self.label_6.setText(_translate("MainWindow", "Height"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page1), _translate("MainWindow", "Input layout"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page2), _translate("MainWindow", "Output layout"))
        self.menuTest.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))

